import "@/app/globals.css";
import Header from "@/components/Header";
import { NextAuthProvider } from "@/providers/NextAuthProvider";
import PreviewPlayer from "@/components/PreviewPlayer";
import Sidebar from "@/components/Sidebar";
import TrackPlayerProvider from "@/providers/TrackPlayerProvider";
import { Montserrat } from "next/font/google";

const fontFamily = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next.js App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <TrackPlayerProvider>
          <body
            className={
              fontFamily.className +
              " h-screen flex flex-col bg-background text-white items-stretch gap-2"
            }
          >
            <div className="grid grid-cols-10 gap-2 p-2">
              <Sidebar />
              {/* <div className="flex rounded-lg bg-paper-700 min-h-screen flex-col ml-[264px]"> */}
              <div className="flex flex-col h-[87vh] overflow-scroll col-span-8 rounded-lg bg-paper-700">
                <Header />
                <main className="mx-8 my-4">{children}</main>
              </div>
            </div>
            <PreviewPlayer />
          </body>
        </TrackPlayerProvider>
      </NextAuthProvider>
    </html>
  );
}
