import "@/app/globals.css";
import Header from "@/components/Header";
import { NextAuthProvider } from "@/components/NextAuthProvider";
import PreviewPlayer from "@/components/PreviewPlayer";
import Sidebar from "@/components/Sidebar";
import TrackPlayerProvider from "@/providers/TrackPlayerProvider";
import { Montserrat } from "next/font/google";

const fontFamily = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <TrackPlayerProvider>
          <body
            className={
              fontFamily.className +
              " text-white p-2 min-h-screen bg-background"
            }
          >
            <Sidebar />
            <div className="flex rounded-lg bg-paper-700 min-h-screen flex-col ml-[264px]">
              <Header />
              <main className="mx-8 my-4">{children}</main>
            </div>
            <PreviewPlayer />
          </body>
        </TrackPlayerProvider>
      </NextAuthProvider>
    </html>
  );
}
